### PR TITLE
Gulp fail build

### PR DESCRIPTION
**Pull request by aekong**
fail the build when gulp-sass errors

### CODE REVIEW

**Comment by aekong** [comment]
Realizing now that I’m requesting a review on a build that’s supposed to fail so this pr has all these red x’s all over it

**Comment by aekong** [comment]
failed as expected here: https://circleci.com/gh/SFDigitalServices/sf-design-system/100
Once merged with fixed master, passes as expected here: https://circleci.com/gh/SFDigitalServices/sf-design-system/101

**Comment by aekong** [comment]
review site: http://ci-101-sfdesignsystem.pantheonsite.io/

**Review by jrubenoff — APPROVED** [review]
LGTM

**Pull request merged**
