### PR TITLE
remove line-height and font-size rem conversion mixins, use px-to-rem…

### PR DESCRIPTION
**Pull request by aekong**
… instead

- will need to do a visual regression on font sizes.

review site here: http://ci-189-sfdesignsystem.pantheonsite.io/

### CODE REVIEW

**Comment by jrubenoff** [comment]
It looks like "Display 1" on the Typography page is broken?

The hero banner looks fine, so I think you just need to fix the `.display-1` CSS class.

**Comment by aekong** [comment]
scaffolding scss didn't import the new function, thanks for catching

**Comment by aekong** [comment]
updated review site: http://ci-189-sfdesignsystem.pantheonsite.io/

**Review by jrubenoff — APPROVED** [review]
🔥

**Pull request merged**
